version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017/mydb
      - AUTH_TOKEN=${AUTH_TOKEN}
      - SIGNING_TOKEN=${SIGNING_TOKEN}

  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      - REACT_APP_SERVER_IP=app:3000

volumes:
  mongodb_data:
